# Generated by Django 4.0 on 2022-04-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_guest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
