# Generated by Django 4.0 on 2022-04-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_car_alter_guest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
