# Generated by Django 4.0 on 2022-04-19 14:23

from django.db import migrations

def create_data(apps, schema_editor):
    Room = apps.get_model('hotel', 'Room')
    Car = apps.get_model('hotel', 'Car')
    
    for n in range(3):
        Room.objects.create(number=n+1001)

    for n in range(3):
        Room.objects.create(number=n+2001)

    for n in range(3):
        Room.objects.create(number=n+3001)
    
    for n in range(3):
        Car.objects.create()

class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_car_available_alter_room_available'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
